/**
 * Integration tests for safeSpace.ts — calculateSafeSpace and related functions.
 *
 * All tests use real panels with finger joints generated by AssemblyBuilder +
 * generatePanelsFromNodes(). Panel.safeSpace is pre-computed in panelBridge.ts
 * so we can access it directly on panels returned by build().
 *
 * Covered functions: calculateSafeSpace (via panel.safeSpace), isPointInSafeSpace,
 * isRectInSafeSpace, isCircleInSafeSpace.
 */
import { describe, it, expect } from 'vitest';
import { AssemblyBuilder } from '../../builder';
import {
  isPointInSafeSpace,
  isRectInSafeSpace,
  isCircleInSafeSpace,
} from '../safeSpace';

// Helper: bounding box of a result-path polygon
function getBounds(path: { x: number; y: number }[]) {
  return {
    minX: Math.min(...path.map(p => p.x)),
    maxX: Math.max(...path.map(p => p.x)),
    minY: Math.min(...path.map(p => p.y)),
    maxY: Math.max(...path.map(p => p.y)),
  };
}

describe('safeSpace integration', () => {

  // ===========================================================================
  // Scenario 1: Face panel result paths exclude joint margins
  // ===========================================================================

  describe('Scenario 1: face panel safe space excludes joint margins', () => {

    it('enclosed box front panel: single result path inset by 2×MT from all four edges', () => {
      const MT = 6;
      const { panels } = AssemblyBuilder
        .enclosedBox(200, 150, 100)
        .withMaterial({ thickness: MT, fingerWidth: 10, fingerGap: 1.5 })
        .build();

      const frontPanel = panels.find(p => p.source.faceId === 'front');
      expect(frontPanel).toBeDefined();

      const safeSpace = frontPanel!.safeSpace;
      expect(safeSpace).toBeDefined();

      const { resultPaths } = safeSpace!;
      const margin = MT * 2; // 2×MT from each jointed edge

      // All 4 edges of the front panel are jointed in a fully enclosed box,
      // so there should be exactly one safe rectangle with no internal obstacles.
      expect(resultPaths.length).toBe(1);

      const bounds = getBounds(resultPaths[0]);
      const halfW = frontPanel!.width / 2;
      const halfH = frontPanel!.height / 2;

      // Each result-path boundary must be inset 2×MT from the body edge.
      expect(bounds.minX).toBeCloseTo(-halfW + margin, 1);
      expect(bounds.maxX).toBeCloseTo(halfW - margin, 1);
      expect(bounds.minY).toBeCloseTo(-halfH + margin, 1);
      expect(bounds.maxY).toBeCloseTo(halfH - margin, 1);
    });

    it('enclosed box: all 6 face panels have result paths strictly inside body bounds', () => {
      const { panels } = AssemblyBuilder
        .enclosedBox(200, 150, 100)
        .build();

      const facePanels = panels.filter(p => p.source.type === 'face');
      expect(facePanels.length).toBe(6);

      for (const panel of facePanels) {
        const safeSpace = panel.safeSpace;
        expect(safeSpace).toBeDefined();
        expect(safeSpace!.resultPaths.length).toBeGreaterThan(0);

        const halfW = panel.width / 2;
        const halfH = panel.height / 2;

        for (const path of safeSpace!.resultPaths) {
          const bounds = getBounds(path);
          // Joint margins mean safe space never reaches the panel edge.
          expect(bounds.minX).toBeGreaterThan(-halfW);
          expect(bounds.maxX).toBeLessThan(halfW);
          expect(bounds.minY).toBeGreaterThan(-halfH);
          expect(bounds.maxY).toBeLessThan(halfH);
        }
      }
    });

    it('enclosed box front panel: reserved regions include joint-edge and joint-margin types', () => {
      const { panels } = AssemblyBuilder
        .enclosedBox(200, 150, 100)
        .build();

      const frontPanel = panels.find(p => p.source.faceId === 'front')!;
      const { reserved } = frontPanel.safeSpace!;

      expect(reserved.length).toBeGreaterThan(0);
      expect(reserved.some(r => r.type === 'joint-edge')).toBe(true);
    });

  });

  // ===========================================================================
  // Scenario 2: Safe space accounts for slot holes and extension regions
  // ===========================================================================

  describe('Scenario 2: safe space accounts for slot holes and extension regions', () => {

    it('top face panel with z-subdivision: small slot holes do not split safe space', () => {
      // A z-axis divider causes the top face panel to receive slot holes (finger
      // tabs from the divider penetrate the face). Each slot hole is small
      // (~fingerWidth × MT), well below the 20% area threshold that would cause
      // a region split. Verify they are tracked in reserved[] but do NOT split
      // resultPaths into multiple rectangles.
      const { panels } = AssemblyBuilder
        .enclosedBox(150, 100, 80)
        .subdivideEvenly('root', 'z', 2)
        .build();

      const topPanel = panels.find(p => p.source.faceId === 'top');
      expect(topPanel).toBeDefined();

      // Slot holes must be present on the top face panel.
      const slotHoles = topPanel!.holes.filter(h => h.source?.type === 'divider-slot');
      expect(slotHoles.length).toBeGreaterThan(0);

      // Each finger-tab slot is small relative to the safe region area, so the
      // safe space remains a single rectangle (no split).
      const { resultPaths } = topPanel!.safeSpace!;
      expect(resultPaths.length).toBe(1);
    });

    it('front panel with bottom extension on jointed edge creates a separate safe region', () => {
      // When a panel has an edge extension larger than MT on a JOINTED edge, the
      // extension area beyond the joint margin is safe to use — but it is not
      // contiguous with the body safe region. A second safe region is created
      // for the extension strip.
      const MT = 3;
      const extensionAmt = 20;
      const { panels } = AssemblyBuilder
        .enclosedBox(150, 100, 80)
        .withMaterial({ thickness: MT, fingerWidth: 10, fingerGap: 1.5 })
        .panel('front')
        .withExtension('bottom', extensionAmt)
        .build();

      const frontPanel = panels.find(p => p.source.faceId === 'front')!;
      const { resultPaths } = frontPanel.safeSpace!;

      // The bottom edge is jointed (enclosed box). The extension (20mm > MT=3mm)
      // triggers a separate safe region beyond the joint for the extension area.
      expect(resultPaths.length).toBe(2);

      // Both the body region and the extension region must have non-zero area.
      for (const path of resultPaths) {
        const bounds = getBounds(path);
        expect(bounds.maxX - bounds.minX).toBeGreaterThan(0);
        expect(bounds.maxY - bounds.minY).toBeGreaterThan(0);
      }
    });

    it('face panel slot exclusions appear in reserved regions with correct types', () => {
      const { panels } = AssemblyBuilder
        .enclosedBox(150, 100, 80)
        .subdivideEvenly('root', 'z', 2)
        .build();

      const topPanel = panels.find(p => p.source.faceId === 'top')!;
      const { reserved } = topPanel.safeSpace!;

      // Reserved regions must include both the raw slot and its margin.
      const slotTypes = reserved.filter(r => r.type === 'slot' || r.type === 'slot-margin');
      expect(slotTypes.length).toBeGreaterThan(0);
    });

    it('divider panel from z-subdivision has safeSpace with valid result paths', () => {
      const { panels } = AssemblyBuilder
        .enclosedBox(150, 100, 80)
        .subdivideEvenly('root', 'z', 2)
        .build();

      const dividerPanel = panels.find(p => p.source.type === 'divider');
      expect(dividerPanel).toBeDefined();

      const safeSpace = dividerPanel!.safeSpace;
      expect(safeSpace).toBeDefined();

      // Divider panel safe space must have at least one result path.
      expect(safeSpace!.resultPaths.length).toBeGreaterThan(0);

      // All result paths must have non-zero area.
      for (const path of safeSpace!.resultPaths) {
        const bounds = getBounds(path);
        expect(bounds.maxX - bounds.minX).toBeGreaterThan(0);
        expect(bounds.maxY - bounds.minY).toBeGreaterThan(0);
      }
    });

  });

  // ===========================================================================
  // Scenario 3: isRectInSafeSpace
  // ===========================================================================

  describe('Scenario 3: isRectInSafeSpace accepts/rejects based on joint margin', () => {

    it('rejects rect whose corner falls inside the top joint margin', () => {
      const MT = 6;
      const { panels } = AssemblyBuilder
        .enclosedBox(200, 150, 100)
        .withMaterial({ thickness: MT, fingerWidth: 10, fingerGap: 1.5 })
        .build();

      const frontPanel = panels.find(p => p.source.faceId === 'front')!;
      const safeSpace = frontPanel.safeSpace!;
      const halfH = frontPanel.height / 2;

      // Center the rect at halfH - MT so its top-right corner reaches halfH - MT + 5,
      // which lies inside the top joint margin [halfH - 2*MT, halfH].
      const rectCenterY = halfH - MT;
      expect(isRectInSafeSpace(0, rectCenterY, 10, 10, safeSpace)).toBe(false);
    });

    it('accepts rect fully inside safe space (centered at origin)', () => {
      const MT = 6;
      const { panels } = AssemblyBuilder
        .enclosedBox(200, 150, 100)
        .withMaterial({ thickness: MT, fingerWidth: 10, fingerGap: 1.5 })
        .build();

      const frontPanel = panels.find(p => p.source.faceId === 'front')!;
      const safeSpace = frontPanel.safeSpace!;

      // Rect at the panel centre is well clear of all joint margins.
      expect(isRectInSafeSpace(0, 0, 10, 10, safeSpace)).toBe(true);
    });

    it('rejects rect whose corner falls inside the left joint margin', () => {
      const MT = 6;
      const { panels } = AssemblyBuilder
        .enclosedBox(200, 150, 100)
        .withMaterial({ thickness: MT, fingerWidth: 10, fingerGap: 1.5 })
        .build();

      const frontPanel = panels.find(p => p.source.faceId === 'front')!;
      const safeSpace = frontPanel.safeSpace!;
      const halfW = frontPanel.width / 2;

      // Center the rect at -halfW + MT so its left edge reaches -halfW + MT - 5,
      // which lies inside the left joint margin [-halfW, -halfW + 2*MT].
      const rectCenterX = -halfW + MT;
      expect(isRectInSafeSpace(rectCenterX, 0, 10, 10, safeSpace)).toBe(false);
    });

    it('accepts rect positioned just past the left joint margin', () => {
      const MT = 6;
      const { panels } = AssemblyBuilder
        .enclosedBox(200, 150, 100)
        .withMaterial({ thickness: MT, fingerWidth: 10, fingerGap: 1.5 })
        .build();

      const frontPanel = panels.find(p => p.source.faceId === 'front')!;
      const safeSpace = frontPanel.safeSpace!;
      const halfW = frontPanel.width / 2;

      // Rect centre placed at -halfW + 2*MT + 10 so its left corner is at
      // -halfW + 2*MT + 5, clearly past the margin boundary.
      const rectCenterX = -halfW + 2 * MT + 10;
      expect(isRectInSafeSpace(rectCenterX, 0, 10, 10, safeSpace)).toBe(true);
    });

  });

  // ===========================================================================
  // Open edge has no joint margin
  // ===========================================================================

  describe('open edge has no joint margin', () => {

    it('basic box (open top): front panel safe space extends to top body edge', () => {
      const MT = 3;
      const { panels } = AssemblyBuilder
        .basicBox(200, 150, 100)
        .withMaterial({ thickness: MT, fingerWidth: 10, fingerGap: 1.5 })
        .build();

      const frontPanel = panels.find(p => p.source.faceId === 'front')!;
      const { resultPaths } = frontPanel.safeSpace!;

      expect(resultPaths.length).toBe(1);
      const bounds = getBounds(resultPaths[0]);
      const halfH = frontPanel.height / 2;

      // Top edge is adjacent to the open 'top' face → no joint → no margin.
      // Safe space maxY must reach the body top edge.
      expect(bounds.maxY).toBeCloseTo(halfH, 1);

      // Bottom edge is adjacent to solid 'bottom' face → has 2×MT margin.
      expect(bounds.minY).toBeCloseTo(-halfH + 2 * MT, 1);
    });

    it('open top vs enclosed: top margin difference is exactly 2×MT', () => {
      const MT = 3;
      const material = { thickness: MT, fingerWidth: 10, fingerGap: 1.5 };

      const { panels: enclosedPanels } = AssemblyBuilder
        .enclosedBox(200, 150, 100)
        .withMaterial(material)
        .build();

      const { panels: openTopPanels } = AssemblyBuilder
        .basicBox(200, 150, 100)
        .withMaterial(material)
        .build();

      const enclosedFront = enclosedPanels.find(p => p.source.faceId === 'front')!;
      const openTopFront = openTopPanels.find(p => p.source.faceId === 'front')!;

      const enclosedMaxY = getBounds(enclosedFront.safeSpace!.resultPaths[0]).maxY;
      const openTopMaxY  = getBounds(openTopFront.safeSpace!.resultPaths[0]).maxY;

      // Enclosed: maxY = halfH - 2*MT. Open-top: maxY = halfH.
      // Difference = 2*MT.
      expect(openTopMaxY - enclosedMaxY).toBeCloseTo(2 * MT, 1);
    });

  });

  // ===========================================================================
  // isPointInSafeSpace
  // ===========================================================================

  describe('isPointInSafeSpace', () => {

    it('returns true for point at panel centre', () => {
      const { panels } = AssemblyBuilder
        .enclosedBox(200, 150, 100)
        .build();

      const frontPanel = panels.find(p => p.source.faceId === 'front')!;
      expect(isPointInSafeSpace(0, 0, frontPanel.safeSpace!)).toBe(true);
    });

    it('returns false for point just inside top joint margin', () => {
      const MT = 3;
      const { panels } = AssemblyBuilder
        .enclosedBox(200, 150, 100)
        .withMaterial({ thickness: MT, fingerWidth: 10, fingerGap: 1.5 })
        .build();

      const frontPanel = panels.find(p => p.source.faceId === 'front')!;
      const halfH = frontPanel.height / 2;

      // y = halfH - 1 is 1 mm from the top edge, deep inside the 2×MT = 6 mm margin.
      expect(isPointInSafeSpace(0, halfH - 1, frontPanel.safeSpace!)).toBe(false);
    });

    it('returns false for point outside the panel outline', () => {
      const { panels } = AssemblyBuilder
        .enclosedBox(200, 150, 100)
        .build();

      const frontPanel = panels.find(p => p.source.faceId === 'front')!;
      const halfW = frontPanel.width / 2;
      const halfH = frontPanel.height / 2;

      expect(isPointInSafeSpace(halfW + 10, 0, frontPanel.safeSpace!)).toBe(false);
      expect(isPointInSafeSpace(0, halfH + 10, frontPanel.safeSpace!)).toBe(false);
    });

  });

  // ===========================================================================
  // isCircleInSafeSpace
  // ===========================================================================

  describe('isCircleInSafeSpace', () => {

    it('returns true for small circle at panel centre', () => {
      const { panels } = AssemblyBuilder
        .enclosedBox(200, 150, 100)
        .build();

      const frontPanel = panels.find(p => p.source.faceId === 'front')!;
      expect(isCircleInSafeSpace(0, 0, 5, frontPanel.safeSpace!)).toBe(true);
    });

    it('returns false for circle whose perimeter enters the top joint margin', () => {
      const MT = 3;
      const { panels } = AssemblyBuilder
        .enclosedBox(200, 150, 100)
        .withMaterial({ thickness: MT, fingerWidth: 10, fingerGap: 1.5 })
        .build();

      const frontPanel = panels.find(p => p.source.faceId === 'front')!;
      const halfH = frontPanel.height / 2;

      // Circle centred 2 mm from the top edge with radius 5 → top of circle
      // extends 3 mm past halfH, entirely outside the safe outline.
      expect(isCircleInSafeSpace(0, halfH - 2, 5, frontPanel.safeSpace!)).toBe(false);
    });

  });

});
