/**
 * Critical Interaction Tests - 3D Viewport
 *
 * These tests exercise the actual browser event flow through React Three Fiber.
 * Unit tests cannot cover this because R3F manages its own event system (raycasting,
 * per-mesh handlers, propagation) independently from the DOM.
 *
 * Motivation: The InteractionManager postmortem (2026-02-25) revealed that 50 unit
 * tests passed but the push-pull arrow click still cancelled the operation in the
 * browser. Browser-level tests are the only way to verify these interactions work.
 *
 * ## How to run
 *
 * 1. Start the dev server: `npm run dev`
 * 2. In another terminal: `npx playwright test tests/e2e/critical-interactions.test.ts`
 *
 * Or with watch mode: `npx playwright test --ui`
 *
 * ## State setup
 *
 * Tests use share links generated by scripts/generate-share-link.ts to pre-apply
 * box state without clicking through the UI. This is faster, more reliable, and
 * exercises the serialization path as a side effect.
 *
 * ## Canvas coordinates
 *
 * The 3D viewport canvas starts at x≈300 (after left sidebar) and y≈50 (after header).
 * Camera is at [150, 150, 150] looking at origin. The default box is centred at origin.
 *
 * Approximate screen coordinates for the default box (200x150x100mm):
 *   - Viewport: 1280x720
 *   - Canvas area: x=[300, 1280], y=[50, 720]
 *   - Canvas center: roughly (790, 385)
 *   - Front face arrow: approximately (620, 450) in screen coords
 *
 * ## Known failing tests
 *
 * `push-pull arrow click — operation is NOT cancelled` is marked `test.fixme()`.
 * Root cause: FloatingPalette uses closeOnClickOutside=true by default, so clicking
 * anywhere outside the palette (including the 3D canvas to interact with the arrow)
 * closes the palette. Fix: pass closeOnClickOutside={false} to the push-pull palette.
 * See: src/components/FloatingPalette.tsx, src/components/PushPullPalette.tsx
 */

import { test, expect, type Page } from '@playwright/test';
import { execSync } from 'child_process';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Generate a share link URL for a preset box configuration. */
function generateShareLink(preset: string): string {
  const output = execSync(
    `npx tsx --import ./scripts/register-lz-compat.mjs scripts/generate-share-link.ts ${preset}`,
    { cwd: process.cwd() }
  ).toString().trim();
  return output;
}

/**
 * Load the app with a basic box via share link.
 * Waits for the 3D canvas to be ready (Three.js initialises asynchronously).
 */
async function loadApp(page: Page, preset: string = 'basic'): Promise<void> {
  const url = generateShareLink(preset);
  await page.goto(url);
  // Wait for the Three.js canvas to be present and the editor toolbar to render
  await page.waitForSelector('.viewport-container canvas');
  await page.waitForSelector('.editor-toolbar');
  // Give Three.js time to render the scene
  await page.waitForTimeout(500);
}

/**
 * Select a face panel by clicking its label in the BoxTree sidebar.
 * More reliable than canvas click because it targets a specific DOM element.
 */
async function selectFaceInTree(page: Page, faceName: string): Promise<void> {
  // The BoxTree renders face panels as tree nodes with labels like "Front", "Back", etc.
  const treeLabel = page.locator('.tree-label', { hasText: faceName }).first();
  await treeLabel.waitFor({ state: 'visible' });
  await treeLabel.click();
}

/**
 * Activate a tool by clicking its button in the EditorToolbar.
 * Uses the title attribute which includes the tool name.
 */
async function activateTool(page: Page, toolTitle: string): Promise<void> {
  const toolBtn = page.locator(`.editor-tool-btn[title*="${toolTitle}"]`);
  await toolBtn.click();
}

// ---------------------------------------------------------------------------
// Tests: App loads and basic navigation
// ---------------------------------------------------------------------------

test.describe('3D Viewport — Critical Interactions', () => {
  test.beforeEach(async ({ page }) => {
    // Set viewport to a consistent size for coordinate-based clicks
    await page.setViewportSize({ width: 1280, height: 720 });
  });

  // -------------------------------------------------------------------------
  // Test 1: App loads and shows 3D canvas
  // -------------------------------------------------------------------------
  test('app loads with box and shows 3D viewport', async ({ page }) => {
    await loadApp(page);

    // Canvas should be visible
    const canvas = page.locator('.viewport-container canvas');
    await expect(canvas).toBeVisible();

    // Editor toolbar should show tool buttons
    const selectBtn = page.locator('.editor-tool-btn[title*="Select"]');
    await expect(selectBtn).toBeVisible();

    const pushPullBtn = page.locator('.editor-tool-btn[title*="Push"]');
    await expect(pushPullBtn).toBeVisible();
  });

  // -------------------------------------------------------------------------
  // Test 2: Click panel in BoxTree selects it
  // Verifies: DOM selection state changes after tree click
  // -------------------------------------------------------------------------
  test('select tool — clicking panel in tree selects it', async ({ page }) => {
    await loadApp(page);

    // Click the Front face in the BoxTree
    await selectFaceInTree(page, 'Front');

    // The tree node for Front should now have 'selected' class
    const frontNode = page.locator('.tree-node-content.panel.selected .tree-label', {
      hasText: 'Front',
    });
    await expect(frontNode).toBeVisible();
  });

  // -------------------------------------------------------------------------
  // Test 3: Click in 3D canvas selects a panel
  // Verifies: R3F pointer events reach panel meshes and update React state
  // -------------------------------------------------------------------------
  test('select tool — click in 3D canvas selects a panel', async ({ page }) => {
    await loadApp(page);

    // Ensure select tool is active
    await activateTool(page, 'Select');

    // Get canvas bounding rect to compute click position
    const canvas = page.locator('.viewport-container canvas');
    const canvasBox = await canvas.boundingBox();
    expect(canvasBox).toBeTruthy();

    // Click roughly in the center of the canvas where a panel should be visible
    const clickX = canvasBox!.x + canvasBox!.width * 0.5;
    const clickY = canvasBox!.y + canvasBox!.height * 0.5;
    await page.mouse.click(clickX, clickY);

    // After clicking, at least one panel should be selected in the tree
    await page.waitForTimeout(300);
    const selectedNode = page.locator('.tree-node-content.panel.selected');
    const count = await selectedNode.count();
    // A click in the center of the canvas should hit the box
    expect(count).toBeGreaterThan(0);
  });

  // -------------------------------------------------------------------------
  // Test 4: Push-pull palette appears when face is selected and tool active
  // Verifies: Operation state machine correctly shows palette with face name
  // -------------------------------------------------------------------------
  test('push-pull palette appears when face is selected and tool is active', async ({ page }) => {
    await loadApp(page);

    // Select the Front face via tree (reliable DOM click)
    await selectFaceInTree(page, 'Front');

    // Activate push-pull tool
    await activateTool(page, 'Push');

    // The floating palette should appear
    const palette = page.locator('.floating-palette');
    await expect(palette).toBeVisible();

    // Palette title should reference the selected face
    const paletteTitle = page.locator('.floating-palette-title');
    await expect(paletteTitle).toContainText('Push/Pull');
    await expect(paletteTitle).toContainText('Front');
  });

  // -------------------------------------------------------------------------
  // Test 5: Push-pull operation survives arrow click (KNOWN BUG — fixme)
  //
  // BUG: FloatingPalette has closeOnClickOutside=true by default. Clicking
  // anywhere in the 3D canvas (outside the palette) closes the palette and
  // cancels the operation. This prevents the user from clicking the push-pull
  // arrow to start dragging.
  //
  // Fix required: PushPullPalette should pass closeOnClickOutside={false} to
  // FloatingPalette. See src/components/PushPullPalette.tsx.
  //
  // Context: InteractionManager postmortem (2026-02-25). The bug was the original
  // impetus for creating this test suite.
  // -------------------------------------------------------------------------
  test.fixme('push-pull arrow click — operation is NOT cancelled', async ({ page }) => {
    await loadApp(page);

    // Step 1: Select the Front face via tree
    await selectFaceInTree(page, 'Front');

    // Step 2: Activate push-pull tool
    await activateTool(page, 'Push');

    // Step 3: Verify palette is visible before the click
    const palette = page.locator('.floating-palette');
    await expect(palette).toBeVisible();

    // Step 4: Click where the push-pull arrow should be rendered.
    // The front face arrow is at approximately (620, 450) in screen space
    // for a 1280x720 viewport with camera at [150,150,150].
    // See the coordinate system docs above.
    await page.mouse.click(620, 450);

    // Wait for any state updates to propagate
    await page.waitForTimeout(300);

    // Step 5: Palette must still be visible — operation was NOT cancelled.
    // This fails because closeOnClickOutside=true causes the palette to close
    // when clicking anywhere outside the palette (including the canvas).
    await expect(palette).toBeVisible();

    // Also verify the push-pull button is still the active tool
    const pushPullBtn = page.locator('.editor-tool-btn.active[title*="Push"]');
    await expect(pushPullBtn).toBeVisible();
  });

  // -------------------------------------------------------------------------
  // Test 6: Push-pull offset input — typing a value updates the offset
  // Verifies: PaletteNumberInput wires to push-pull state correctly
  //
  // NOTE: We test via direct input rather than 3D canvas drag because the
  // canvas drag is blocked by the same closeOnClickOutside bug as test 5.
  // Once the bug is fixed, a separate canvas-drag test should be added.
  // -------------------------------------------------------------------------
  test('push-pull offset input — typing changes the offset value', async ({ page }) => {
    await loadApp(page);

    // Select Front face and activate push-pull
    await selectFaceInTree(page, 'Front');
    await activateTool(page, 'Push');

    // Verify the push-pull palette is visible with offset input
    const palette = page.locator('.floating-palette');
    await expect(palette).toBeVisible();

    // The number input field shows the current offset
    // PaletteNumberInput → NumberInput → .number-input-field
    const offsetInput = page.locator('.number-input-field').first();
    await expect(offsetInput).toBeVisible();
    const initialValue = await offsetInput.inputValue();
    expect(Number(initialValue)).toBe(0);

    // Type a new offset value directly into the input
    await offsetInput.click(); // Focus the input
    await offsetInput.fill('20'); // Type 20mm
    await page.waitForTimeout(200);

    // The palette should still be visible (we interacted with the palette, not outside it)
    await expect(palette).toBeVisible();

    // Verify the offset value changed
    const updatedValue = await offsetInput.inputValue();
    expect(Number(updatedValue)).toBe(20);
  });

  // -------------------------------------------------------------------------
  // Test 6b: Push-pull drag — canvas drag (KNOWN BUG — fixme)
  //
  // BUG: Same root cause as test 5 (closeOnClickOutside=true). The mouse.down()
  // in the canvas triggers the FloatingPalette's click-outside handler which
  // closes the palette. The drag interaction cannot be tested until the bug is fixed.
  // -------------------------------------------------------------------------
  test.fixme('push-pull drag — drag arrow in canvas changes offset', async ({ page }) => {
    await loadApp(page);

    await selectFaceInTree(page, 'Front');
    await activateTool(page, 'Push');

    const palette = page.locator('.floating-palette');
    await expect(palette).toBeVisible();

    const canvas = page.locator('.viewport-container canvas');
    const canvasBox = await canvas.boundingBox();
    expect(canvasBox).toBeTruthy();

    // Drag from front face arrow position upward
    const dragStartX = canvasBox!.x + canvasBox!.width * 0.4;
    const dragStartY = canvasBox!.y + canvasBox!.height * 0.65;

    await page.mouse.move(dragStartX, dragStartY);
    await page.mouse.down();
    await page.waitForTimeout(50);
    await page.mouse.move(dragStartX, dragStartY - 40, { steps: 8 });
    await page.mouse.up();
    await page.waitForTimeout(300);

    // Should still be visible after drag (this fails because of closeOnClickOutside)
    await expect(palette).toBeVisible();

    // Offset should have changed
    const offsetInput = page.locator('.number-input-field').first();
    const updatedValue = await offsetInput.inputValue();
    expect(Number(updatedValue)).not.toBe(0);
  });

  // -------------------------------------------------------------------------
  // Test 7: Enter 2D sketch view via BoxTree "Edit in 2D" button
  // Verifies: enterSketchView() fires and view mode switches to '2d'
  // -------------------------------------------------------------------------
  test('edit-in-2D button in tree enters 2D sketch view', async ({ page }) => {
    await loadApp(page);

    // Select Front face first (makes the Edit button visible)
    await selectFaceInTree(page, 'Front');

    // Hover over the Front face tree node to reveal tree controls
    const frontLabel = page.locator('.tree-label', { hasText: 'Front' }).first();
    await frontLabel.hover();

    // Click the "Edit in 2D" button (title="Edit in 2D")
    const frontTreeNode = page.locator('.tree-node-content.panel', {
      has: page.locator('.tree-label', { hasText: 'Front' }),
    }).first();
    const editBtn = frontTreeNode.locator('.tree-btn[title="Edit in 2D"]').first();
    await editBtn.click();

    // 2D sketch view should now be active
    const sketchView = page.locator('.sketch-view-2d');
    await expect(sketchView).toBeVisible();
  });

  // -------------------------------------------------------------------------
  // Test 8: Orbit — drag on empty canvas area changes the view
  // Verifies: OrbitControls receives drag events and rotates the camera
  // -------------------------------------------------------------------------
  test('orbit — drag on empty canvas area changes camera view', async ({ page }) => {
    await loadApp(page);

    // Drag in the upper-right area of the canvas where there should be empty space
    const canvas = page.locator('.viewport-container canvas');
    const canvasBox = await canvas.boundingBox();
    expect(canvasBox).toBeTruthy();

    // Upper-right corner of canvas — empty space away from the box
    const startX = canvasBox!.x + canvasBox!.width * 0.85;
    const startY = canvasBox!.y + canvasBox!.height * 0.15;

    // Take screenshot before drag
    const screenshotBefore = await canvas.screenshot();

    // Perform orbit drag
    await page.mouse.move(startX, startY);
    await page.mouse.down();
    await page.mouse.move(startX - 100, startY + 50, { steps: 10 });
    await page.mouse.up();

    // Wait for Three.js to re-render
    await page.waitForTimeout(300);

    // Take screenshot after drag
    const screenshotAfter = await canvas.screenshot();

    // The screenshots should differ — camera has moved
    const isDifferent = Buffer.compare(screenshotBefore, screenshotAfter) !== 0;
    expect(isDifferent).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Tests: Push-pull operation state management
// ---------------------------------------------------------------------------

test.describe('Push-pull operation — state management', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
  });

  // -------------------------------------------------------------------------
  // Test 9: Escape key cancels push-pull operation
  // -------------------------------------------------------------------------
  test('pressing Escape cancels push-pull operation', async ({ page }) => {
    const url = generateShareLink('basic');
    await page.goto(url);
    await page.waitForSelector('.viewport-container canvas');
    await page.waitForTimeout(500);

    // Select front face and activate push-pull
    await page.locator('.tree-label', { hasText: 'Front' }).first().click();
    await page.locator('.editor-tool-btn[title*="Push"]').click();

    // Verify palette is visible
    await expect(page.locator('.floating-palette')).toBeVisible();

    // Press Escape to cancel
    await page.keyboard.press('Escape');
    await page.waitForTimeout(200);

    // Palette should be gone (operation cancelled)
    await expect(page.locator('.floating-palette')).not.toBeVisible();
  });

  // -------------------------------------------------------------------------
  // Test 10: Switching to select tool closes push-pull palette
  // -------------------------------------------------------------------------
  test('switching to select tool closes push-pull palette', async ({ page }) => {
    const url = generateShareLink('basic');
    await page.goto(url);
    await page.waitForSelector('.viewport-container canvas');
    await page.waitForTimeout(500);

    // Select front face and activate push-pull
    await page.locator('.tree-label', { hasText: 'Front' }).first().click();
    await page.locator('.editor-tool-btn[title*="Push"]').click();

    // Verify palette is visible
    await expect(page.locator('.floating-palette')).toBeVisible();

    // Switch to select tool
    await page.locator('.editor-tool-btn[title*="Select"]').click();
    await page.waitForTimeout(200);

    // Palette should be gone
    await expect(page.locator('.floating-palette')).not.toBeVisible();
  });
});
